package com.example.schoolerp.DataClasses

data class AllStudentData (
    val additional_note: String,
    val address: String,
    val blood_group: String,
    val cast: String,
    val created_at: String,
    val discount_fee: String,
    val disease_if_any: String,
    val dt_of_admission: String,
    val dt_of_birth: String,
    val education: String,
    val family: String,
    val father_education: String,
    val father_id: String,
    val father_name: String,
    val father_occupation: String,
    val gender: String,
    val id: String,
    val identity_mark: String,
    val mobile_no: String,
    val mother_id: String,
    val mother_name: String,
    val orphan_student: String,
    val osc: String,
    val picture: String,
    val previous_id: String,
    val previous_school: String,
    val registration_no: String,
    val religion: String,
    val school_id: String,
    val siblings: String,
    val st_class: String,
    val st_name: String
)