package com.example.schoolerp.models.responses

data class LoginResponse(
    val status: Boolean,
    val message: String,
    val role: String,
    val school_id: String,
    val number: String,
    val school_name: String,
    val employee_id: String,
    val institute_address: String,
    val institute_logo: String,
    val roll_no: String,
    val picture:String,
    val tag_line: String,
    val phone_number: String,
    val password: String,
    val website: String,
    val country: String,
    val updated_at: String,
    //===========student response//=====
    val st_name:String,
    val registration_no:String,
    val st_class:String,
    val student_id:String,
    val dt_of_admission:String,
    val username:String,
    val st_status:String,
    val dt_of_birth:String,
    val discount_fee:String,
    val religion:String,
    val cast:String,
    val gender:String,
    val blood_group:String,
    val family:String,
    val siblings:String,
    val orphan_student:String,
    val osc:String,
    val st_previous_school:String,
    val previous_id:String,
    val disease_if_any:String,
    val identification_mark:String,
    val address:String,
    val father_name:String,
    val father_id:String,
    val father_education:String,
    val father_mobile:String,
    val father_profession:String,
    val father_occupation:String,
    val father_income:String,
    val mother_name:String,
    val mother_mobile:String,
    val mother_id:String,
    val mother_education:String,
    val mother_profession:String,
    val mother_occupation:String,
    val mother_income:String,
    //=========Principale=======
//    val status: Boolean,
//    val message: String,
//    val role: String,
//    val school_id: String,
    val employee_name: String,
//    val number: String,
    val date_of_joining: String,
    val monthly_salary: String,
    val f_h_name: String,
    val national_id: String,
    val education: String,

//    val gender: String,
//    val religion: String,
//    val blood_group: String,
    val experience: String?,
    val date_of_birth: String,
    val home_address: String,
    val email: String?,
//    val username: String,
//    val password: String,
//    val st_status: String,
    val users: List<User>
)


data class User(
    val id: String,
    val school_name: String,
    val employee_id: String,
    val password: String,
    val number: String,
    val created_at: String,
    val school_id: String,
    val address: String,
    val website: String,
    val tag_line: String,
//    val website: String,
    val role: String
)

data class loginStudentResposne(
    val status: Boolean,
    val message: String,
    val role: String
)
